### ISSUE TITLE
3.16.3 kernel oops on boot (8089D)

### ISSUE THREAD

**Issue by iptux** [biergaizi/loongson-sources#2]
got a kernel call trace on boot

```
CPU 0 Unable to handle kernel paging request at virtual address 0000000100000000, epc == 0000000100000000, ra == ffffffff8057ba24
```

for full kernel log see http://paste.ubuntu.com/8392558/

**Comment by biergaizi** [comment]
I have identified the problem, it's a C programming 101 mistake. To handle events from the Embedded Controller, we define a lookup table,

```
static const struct sci_event se[] = {
	[EVENT_AC_BAT] = {0, ac_bat_handler},
	[EVENT_AUDIO_MUTE] = {REG_AUDIO_MUTE, NULL},
	[EVENT_AUDIO_VOLUME] = {REG_AUDIO_VOLUME, NULL},
	[EVENT_CRT_DETECT] = {REG_CRT_DETECT, crt_detect_handler},
	[EVENT_CAMERA] = {REG_CAMERA_STATUS, camera_handler},
	[EVENT_BLACK_SCREEN] = {REG_DISPLAY_LCD, displaytoggle_handler},
	[EVENT_DISPLAY_BRIGHTNESS] = {REG_DISPLAY_BRIGHTNESS, NULL},
	[EVENT_LID] = {REG_LID_DETECT, NULL},
	[EVENT_DISPLAY_TOGGLE] = {0, switchvideomode_handler},
	[EVENT_USB_OC0] = {REG_USB2_FLAG, usb0_handler},
	[EVENT_USB_OC2] = {REG_USB2_FLAG, usb2_handler},
	[EVENT_WLAN] = {REG_WLAN, NULL},
};
```

This array initialization syntax is a GNU extension. It defines the corresponding values at the right side, using the index from the left side. The length of the array will be the maximum index appeared from the left side. 

However, if the Embedded Controller fires an unlisted event, it may trigger an invalid pointer deferences if the value is greater than the largest index. The solution is easy: add a stub value at the beginning, and another stub value at the end, and check if the event is located within the range. 

In fact, the original developers have already thought about it,

```
enum {
	EVENT_LID = 0x23,	/*  LID open/close */
	EVENT_DISPLAY_TOGGLE,	/*  Fn+F3 for display switch */
	EVENT_SLEEP,		/*  Fn+F1 for entering sleep mode */
	EVENT_OVERTEMP,		/*  Over-temperature happened */
	EVENT_CRT_DETECT,	/*  CRT is connected */
	EVENT_CAMERA,		/*  Camera on/off */
	EVENT_USB_OC2,		/*  USB2 Over Current occurred */
	EVENT_USB_OC0,		/*  USB0 Over Current occurred */
	EVENT_BLACK_SCREEN,	/*  Turn on/off backlight */
	EVENT_AUDIO_MUTE,	/*  Mute on/off */
	EVENT_DISPLAY_BRIGHTNESS,/* LCD backlight brightness adjust */
	EVENT_AC_BAT,		/*  AC & Battery relative issue */
	EVENT_AUDIO_VOLUME,	/*  Volume adjust */
	EVENT_WLAN,		/*  Wlan on/off */
	EVENT_END
};
```

But another developer probably missed the purpose of `EVENT_END`...

**Comment by biergaizi** [comment]
The drivers are currently being reworked to be submitted into the mainline.
